# Generated by Django 6.0.6 on 2026-06-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Kirish'), ('exit', 'Chiqish')], max_length=10)),
                ('verify_type', models.CharField(choices=[('face', 'Yuz tanish'), ('card', 'Karta'), ('face_card', 'Yuz + Karta')], default='face', max_length=20)),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('is_authorized', models.BooleanField(default=True, verbose_name='Ruxsat berilgan')),
                ('raw_data', models.JSONField(default=dict, verbose_name='ISUP raw data')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name="Harorat (agar bo'lsa)")),
                ('mask_detected', models.BooleanField(blank=True, null=True, verbose_name='Niqob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='devices.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Kirish/chiqish eventi',
                'verbose_name_plural': 'Kirish/chiqish eventlari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Ishlagan vaqt (daqiqa)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='employees.employee')),
                ('entry_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.accessevent')),
                ('exit_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.accessevent')),
            ],
            options={
                'verbose_name': 'Ish sessiyasi',
                'verbose_name_plural': 'Ish sessiyalari',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['timestamp'], name='events_acce_timesta_9ce7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['device', 'timestamp'], name='events_acce_device__a953d5_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['employee', 'timestamp'], name='events_acce_employe_132871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worksession',
            unique_together={('employee', 'date')},
        ),
    ]
